# Generated by Django 5.0.2 on 2024-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_questionpattern_random_serve'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('drag_and_drop', 'Drag and Drop'), ('dropdown', 'Dropdown')], default='single-choice', max_length=50),
        ),
    ]
