# Generated by Django 5.0.2 on 2024-07-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('drag_and_drop', 'Drag and Drop'), ('dropdown', 'Dropdown')], default='single_choice', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.questionpattern'),
        ),
    ]
