# Generated by Django 5.0.2 on 2024-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_singlechoicequestion_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
