# Generated by Django 5.0.2 on 2024-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_questionpattern_instructor_questionpattern_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpattern',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
