# Generated by Django 5.0.2 on 2024-06-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_questionpattern_pattern_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpattern',
            old_name='pattern_name',
            new_name='pattern',
        ),
    ]
